/* Musl integration source. */
#define SYS_read             0
#define SYS_write            1
#define SYS_close            3
#define SYS_mmap             9
#define SYS_mprotect        10
#define SYS_munmap          11
#define SYS_brk             12
#define SYS_rt_sigaction    13
#define SYS_rt_sigprocmask  14
#define SYS_ioctl            16
#define SYS_poll             7
#define SYS_dup              32
#define SYS_dup2             33
#define SYS_nanosleep        35
#define SYS_getpid           39
#define SYS_socket           41
#define SYS_connect          42
#define SYS_accept           43
#define SYS_sendto           44
#define SYS_recvfrom         45
#define SYS_shutdown         48
#define SYS_bind             49
#define SYS_listen           50
#define SYS_clone            56
#define SYS_futex           202
#define SYS_set_tid_address 218
#define SYS_exit_group      231
#define SYS_openat          257
#define SYS_epoll_create1   291
#define SYS_epoll_ctl       233
#define SYS_epoll_wait      232
#define SYS_eventfd2        290
#define SYS_timerfd_create  283
#define SYS_timerfd_settime 286
#define SYS_arch_prctl      158
